<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE exceptioninfo [
	<!ELEMENT exceptioninfo (exception+) >
	<!ELEMENT exception (messagecode,contextind?,((confirmationind,loggingtype)|loggingtype)?) >
	<!ATTLIST exception name CDATA #REQUIRED>
	<!ELEMENT messagecode (#PCDATA)>
	<!ELEMENT contextind (#PCDATA)>
	<!ELEMENT confirmationind (#PCDATA)>
	<!ELEMENT loggingtype (#PCDATA)>
]>

<exceptioninfo>
	<exception name="NoAreasFoundException">
		<messagecode>abc.expError.noAreasFound</messagecode>
	</exception>
	<exception name="ServiceActiveAtStoresException">
		<messagecode>expError.serviceActiveAtStores</messagecode>
     	<confirmationind>true</confirmationind>
     	<loggingtype>nologging</loggingtype>
	</exception>
	<exception name="ViocUniqueConstraintException">
		<messagecode>expError.uniqueconstraint</messagecode>
		<contextind>true</contextind>
	</exception>
	
		
	<exception name="BussMasterDataMissingException">
		<messagecode>expError.buss.masterDataMissing</messagecode>
	</exception>
	<exception name="BussTestCannotGeneratedException">
		<messagecode>expError.buss.testCannotBeGenerated</messagecode>
	</exception>
	<exception name="DBDataOutOfRangeException">
		<messagecode>expError.db.dataOutOfRange</messagecode>
	</exception>
	<exception name="DBDataSourceException">
		<messagecode>expError.db.DBConnCannotBEDone</messagecode>
	</exception>
	<exception name="DBIntegrityViolationException">
		<messagecode>expError.db.integrity</messagecode>
	</exception>
	<exception name="DBInvalidDataInsertionException">
		<messagecode>expError.db.someDataMissing</messagecode>
	</exception>
	<exception name="DBInvalidDBDriverException">
		<messagecode>expError.db.DbDriverCannotBELoaded</messagecode>
	</exception>	
</exceptioninfo>